### ISSUE TITLE
all_same() - check all elements in vector are the same

### ISSUE THREAD

**Issue by 1danjordan** [tidyverse/funs#19]
Ran into this a few times in the last week and thought it might belong here:

```r
all_same(1:10)         # FALSE
all_same(rep(1,10))    # TRUE
```

Some old discussion [here](https://stat.ethz.ch/pipermail/r-help/2005-August/078129.html) on the mailing list regarding this. I don't know how efficient the suggested `all(x == x[1])` or whether it is suitable across all modes, but has been very handy in dplyr chains, trying to work out all the elements of a variable in a grouped dataframe are the same:

```r
all_same <- function(x) all(x == x[1])

mtcars %>% 
  group_by(carb) %>%
  summarise(all_same(am))

##  A tibble: 6 x 2
#    carb `all_same(am)`
#   <dbl>          <lgl>
# 1     1          FALSE
# 2     2          FALSE
# 3     3           TRUE
# 4     4          FALSE
# 5     6           TRUE
# 6     8           TRUE
```

**Comment by hadley** [comment]
Now at `vctrs::vec_duplicate_all()`
