### ISSUE TITLE
README, lifecycle, and CRAN availability expectations

### ISSUE THREAD

**Issue by jayqi** [tidyverse/funs#47]
Hello,

It would be very helpful for this package to have a README describing its purpose, and how it relates to other R packages, and when one could expect the functionality to be available. The [DESCRIPTION](https://github.com/r-lib/funs/blob/master/DESCRIPTION) file only says "Useful vectorised function" which is not that clear. 

For example, it seems like the work done in this repository is some manner of future dependency for dplyr. I was directed to this repo when asking about `dplyr::between` support for character vectors (https://github.com/tidyverse/dplyr/issues/5122). It looks like this has been implemented already and the associated issue is closed (#26), but it's not clear when this will make it back to dplyr. 

Will this package make it to CRAN, and if so, roughly when? 

Additionally, it would be helpful if there was a lifecycle designation like what the other tidyverse packages use. 

Thank you!

**Comment by hadley** [comment]
This package is many just a collection of notes at this time.
