### ISSUE TITLE
Should this repo live in tidyverse?

### ISSUE THREAD

**Issue by hadley** [tidyverse/funs#49]
And does it need a better name?

**Comment by DavisVaughan** [comment]
{fns} with `fn_*()` prefix?

```r
fn_if_else()
fn_cumany()
fn_coalesce()
```

- not saying we need to prefix, but it's an interesting option since we seem to use `fn` to mean "function" in many places

- and it kind of matches the naming convention of vctrs with being plural and having no vowels

**Comment by hadley** [comment]
These functions kind of feel like they should be prefix-less to me. (And using a prefix to indicate that a function is a function seems weird 🤪)

**Comment by romainfrancois** [comment]
I think we can close this, if we really want to change the name, this will come back without an issue :p
