### ISSUE TITLE
`coalesce()` invariants

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/funs#64]
Right now `coalesce()` takes `...` and takes the common type and size of its inputs. In funs, having 0 inputs returns `NULL`, in dplyr it is an error.

I had mentioned here https://github.com/tidyverse/funs/issues/17#issuecomment-546110237 that the signature could instead be `coalesce(x, ...)`

This would:
- Require at least 1 input in a straightforward way
- Have size and type stability on `x`

I tend to think of `coalesce()` as "this first input is the one I care about, but fill in its holes using subsequent inputs", so these invariants make sense to me. Maybe I shouldn't think about it that way, or maybe I'm thinking of a different function that we could also add to funs?

Update: What I am thinking of is sort of like a mix of `tidyr::replace_na()` and `coalesce()`

**Comment by hadley** [comment]
That framing seems solid to me.
