### ISSUE TITLE
coalesce on a single column (typically with summarize)

### ISSUE THREAD

**Issue by torbjorn** [tidyverse/funs#68]
Can `coalesce` be changed to also do this as it would intuitively make sense to do it?

```r

> (d <- data.frame( grp = c(1,1), x=c(NA,1) ))
  grp  x
1   1 NA
2   1  1

## Now this doesn't do away with the NA:

> d %>% group_by(grp) %>% summarise( x = coalesce(x) )
`summarise()` has grouped output by 'grp'. You can override using the `.groups` argument.
# A tibble: 2 x 2
# Groups:   grp [1]
    grp     x
  <dbl> <dbl>
1     1    NA
2     1     1

## but this finally does:

> d %>% group_by(grp) %>% summarize( x = do.call( coalesce, as.list(x) ) )
# A tibble: 1 x 2
    grp     x
  <dbl> <dbl>
1     1     1

```

I guess you can only pull something in so many directions, and `coalesce` is perhaps over-stretched. Or just right stretched. What about a `coalesce_v` or something for this purpose? na.omit, reduce or filter don't really offer working alternatives I'd say.

**Comment by DavisVaughan** [comment]
Is this much different from:

``` r
d <- data.frame( grp = c(1,1), x=c(NA,1) )

tidyr::drop_na(d, x)
#>   grp x
#> 1   1 1
```

<sup>Created on 2021-05-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by hadley** [comment]
This is definitely not a job for `coalesce()`. As @DavisVaughan suggest you can use `drop_na()` or you could use `across()`:


``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(grp = c(1, 1), x = c(NA, 1))
df %>%
  filter(if_all(everything(), ~ !is.na(x)))
#>   grp x
#> 1   1 1
```

<sup>Created on 2021-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by felipegerard** [comment]
There are some cases where this makes sense. For instance, if you have 2 columns, one with an ID and one with an attribute, and for some reason, the attribute is empty in some rows, you might want to do something like this:
```
d <- data.frame(store_id = c(1,1), store_type = c(NA, 'large'), month = c(1, 2), sales = c(10, 20))
d %>%
  group_by(store_id) %>%
  summarise(
    store_type = coalesce_s(store_type),
    sales = sum(sales)
  )
```

Note you can't group by `store_type` because it is incomplete and inconsistent across rows. You could use `do.call(coalesce, as.list(store_type))`, but that is really slow.

You could use a function like this, just with a more robust and faster implementation:
```
coalesce_summary <- function(x) {
  if (all(is.na(x))) {
    NA
  } else {
    first(x[!is.na(x)])
  }
}
```
